version: '3.7'

services:
  db:
    image: postgres:11-alpine
    container_name: simple_admin
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - ./.env
    ports:
      - 5432:5432
